# Generated by Django 4.2.11 on 2025-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_options_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('INR', 'Indian Rupee (₹)')], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('other', 'Other'), ('online', 'Online'), ('check', 'By Check (Bank Transfer)'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('other', 'Other'), ('online', 'Online'), ('check', 'By Check (Bank Transfer)'), ('cash', 'Cash')], max_length=20),
        ),
    ]
